----------------------------------------------------------------------------------
-- Creates a 1 clk wide pulse at the rate specified by the divideby generic.
-- Note - this pulse is to be used as an enable, not a clk! 
-- (it is generated by combinational logic after all)
----------------------------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY clkdivider IS
	GENERIC (divideby : NATURAL := 2);
	PORT (
		clk : IN STD_LOGIC;
		resetn : IN STD_LOGIC;
		pulseout : OUT STD_LOGIC);
END clkdivider;
ARCHITECTURE Behavioral OF clkdivider IS
	SIGNAL cnt : NATURAL RANGE 0 TO divideby - 1 := 0;
BEGIN

	PROCESS (clk, resetn)
	BEGIN
		IF rising_edge(clk) THEN
			IF resetn = '0' THEN
				cnt <= 0;
			ELSE
				IF (cnt = divideby - 1) THEN
					cnt <= 0;
				ELSE
					cnt <= cnt + 1;
				END IF;
			END IF;
		END IF;
	END PROCESS;
	pulseout <= '1' WHEN cnt = divideby - 1 ELSE
		'0';
END Behavioral;